### ISSUE TITLE
1.11.2-1.0.0 crashes dedicated Forge 1.11.2 build 2223 on startup

### ISSUE THREAD

**Issue by kreezxil** [Shadows-of-Fire/Mob-Farm#1]
Notes:
     class not found exception

crash report:
https://gist.github.com/849dfbdca358b96a4e8201327e96d5e7

fml server latest:
https://gist.github.com/c55fd5c4a7c9fbd3aa007c0ba3e77f3e

**Comment by Shadows-of-Fire** [comment]
Welp... I deleted that file and forgot to update the ref to the CommonProxy.  Gimme 10 minutes.

**Comment by kreezxil** [comment]
Cool, thanks 

-----Original Message-----
