### ISSUE TITLE
[1.11.2-1.2.2] can't harvest mob

### ISSUE THREAD

**Issue by kreezxil** [Shadows-of-Fire/Mob-Farm#4]
right click mob, it flickers and nothing happens.

also there are no messages in either ssp or smp consoles.

**Comment by Shadows-of-Fire** [comment]
Can't reproduce this at all. I'll reupload the jar as 1.2.3, but this issue is not apparent or reproducible.  
Unless you're in peaceful that is, in which case, this isn't an issue, you can't spawn mobs in peaceful.
