### ISSUE TITLE
1.12.1: No drops but seed for skeleton crops

### ISSUE THREAD

**Issue by Knito58** [Shadows-of-Fire/Mob-Farm#7]
MC 1.12.1, Forge 14.22.0.2456, Mob Farm 1.12-2.2.1, Gamemode SSP

The only seed I was interested in and which I tested was skeleton seed as this is necessary for the wither skeleton. TOP said: "Fully grown" as the grow state of the crops.

But when harvesting the fully grown skeleton crops there is only seeds generated. Neither mobs nor drops.

**Comment by Shadows-of-Fire** [comment]
So like, unless you're playing in peaceful, the thing works just fine.  Cannot reproduce.
